// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v12 "htpasswd-operator/pkg/apis/htpasswduser/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/testing"
)

// FakeHtpasswdUsers implements HtpasswdUserInterface
type FakeHtpasswdUsers struct {
	Fake *FakeFlangaV1
	ns   string
}

var htpasswdusersResource = v12.SchemeGroupVersion.WithResource("htpasswdusers")

var htpasswdusersKind = v12.SchemeGroupVersion.WithKind("HtpasswdUser")

// Get takes name of the htpasswdUser, and returns the corresponding htpasswdUser object, and an error if there is any.
func (c *FakeHtpasswdUsers) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v12.HtpasswdUser, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(htpasswdusersResource, c.ns, name), &v12.HtpasswdUser{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v12.HtpasswdUser), err
}

// List takes label and field selectors, and returns the list of HtpasswdUsers that match those selectors.
func (c *FakeHtpasswdUsers) List(ctx context.Context, opts metav1.ListOptions) (result *v12.HtpasswdUserList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(htpasswdusersResource, htpasswdusersKind, c.ns, opts), &v12.HtpasswdUserList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v12.HtpasswdUserList{ListMeta: obj.(*v12.HtpasswdUserList).ListMeta}
	for _, item := range obj.(*v12.HtpasswdUserList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested htpasswdUsers.
func (c *FakeHtpasswdUsers) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(htpasswdusersResource, c.ns, opts))

}

// Create takes the representation of a htpasswdUser and creates it.  Returns the server's representation of the htpasswdUser, and an error, if there is any.
func (c *FakeHtpasswdUsers) Create(ctx context.Context, htpasswdUser *v12.HtpasswdUser, opts metav1.CreateOptions) (result *v12.HtpasswdUser, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(htpasswdusersResource, c.ns, htpasswdUser), &v12.HtpasswdUser{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v12.HtpasswdUser), err
}

// Update takes the representation of a htpasswdUser and updates it. Returns the server's representation of the htpasswdUser, and an error, if there is any.
func (c *FakeHtpasswdUsers) Update(ctx context.Context, htpasswdUser *v12.HtpasswdUser, opts metav1.UpdateOptions) (result *v12.HtpasswdUser, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(htpasswdusersResource, c.ns, htpasswdUser), &v12.HtpasswdUser{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v12.HtpasswdUser), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeHtpasswdUsers) UpdateStatus(ctx context.Context, htpasswdUser *v12.HtpasswdUser, opts metav1.UpdateOptions) (*v12.HtpasswdUser, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(htpasswdusersResource, "status", c.ns, htpasswdUser), &v12.HtpasswdUser{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v12.HtpasswdUser), err
}

// Delete takes name of the htpasswdUser and deletes it. Returns an error if one occurs.
func (c *FakeHtpasswdUsers) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(htpasswdusersResource, c.ns, name, opts), &v12.HtpasswdUser{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHtpasswdUsers) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(htpasswdusersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v12.HtpasswdUserList{})
	return err
}

// Patch applies the patch and returns the patched htpasswdUser.
func (c *FakeHtpasswdUsers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v12.HtpasswdUser, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(htpasswdusersResource, c.ns, name, pt, data, subresources...), &v12.HtpasswdUser{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v12.HtpasswdUser), err
}
