// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/mowirth/htpasswd-operator/pkg/client/clientset/versioned/typed/htpasswduser/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeFlangaV1 struct {
	*testing.Fake
}

func (c *FakeFlangaV1) HtpasswdUsers(namespace string) v1.HtpasswdUserInterface {
	return &FakeHtpasswdUsers{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeFlangaV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
