// Code generated by lister-gen. DO NOT EDIT.

package v1

// HtpasswdUserListerExpansion allows custom methods to be added to
// HtpasswdUserLister.
type HtpasswdUserListerExpansion interface{}

// HtpasswdUserNamespaceListerExpansion allows custom methods to be added to
// HtpasswdUserNamespaceLister.
type HtpasswdUserNamespaceListerExpansion interface{}
