apiVersion: apps/v1
kind: Deployment
metadata:
  name: htpasswd-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: example
    spec:
      serviceAccountName: htpasswd-controller-sa
      containers:
        - name: htpasswd-operator
          image: mowirth/htpasswd-operator:latest
          volumeMounts:
            - name: data
              mountPath: /auth
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: HTPASSWD_FILE
              value: /auth/htpasswd
            - name: LOG_LEVEL
              value: DEBUG
        - name: registry
          image: registry:latest
          volumeMounts:
            - name: data
              mountPath: "/auth"
              readOnly: true
          env:
            - name: REGISTRY_AUTH
              value: "htpasswd"
            - name: REGISTRY_AUTH_HTPASSWD_REALM
              value: "Registry Realm"
            - name: REGISTRY_AUTH_HTPASSWD_PATH
              value: "/auth/htpasswd"
            - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
              value: /data
          ports:
            - containerPort: 5000
              name: registry-http
              protocol: TCP
      volumes:
        - name: data
          emptyDir: { }
