apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: htpasswdusers.flanga.io
spec:
  group: flanga.io
  names:
    kind: HtpasswdUser
    singular: htpasswduser
    plural: htpasswdusers
  scope: Namespaced
  versions:
    - name: v1
      additionalPrinterColumns:
        - jsonPath: .status.conditions[0].message
          name: Status
          type: string
        - jsonPath: .status.conditions[0].status
          name: Configured
          type: string
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      subresources:
        status: {}
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: HtpasswdUser reflects reflect an user/password in a operator file
          type: object
          required:
            - spec
            - apiVersion
            - kind
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              anyOf:
                - required:
                    - username
                    - password
              properties:
                username:
                  type: object
                  oneOf:
                    - required: [ configMapKeyRef ]
                    - required: [ secretKeyRef ]
                    - required: [ value ]
                  properties:
                    configMapKeyRef:
                      type: object
                      required:
                        - name
                        - key
                      properties:
                        name:
                          type: string
                        key:
                          type: string
                        optional:
                          type: boolean
                    secretKeyRef:
                      type: object
                      required:
                        - name
                        - key
                      properties:
                        name:
                          type: string
                        key:
                          type: string
                        optional:
                          type: boolean
                    value:
                      type: string
                password:
                  type: object
                  oneOf:
                    - required: [ configMapKeyRef ]
                    - required: [ secretKeyRef ]
                    - required: [ value ]
                  properties:
                    configMapKeyRef:
                      type: object
                      required:
                        - name
                        - key
                      properties:
                        name:
                          type: string
                        key:
                          type: string
                        optional:
                          type: boolean
                    secretKeyRef:
                      type: object
                      required:
                        - name
                        - key
                      properties:
                        name:
                          type: string
                        key:
                          type: string
                        optional:
                          type: boolean
                    value:
                      type: string
            status:
              description: HtpasswdUserStatus is the most recently observed status of the HtpasswdUser.
              properties:
                conditions:
                  description: Represents the latest available observations of a operator user's current state.
                  items:
                    description: HtpasswdUserCondition describes the state of a operator user at a certain point.
                    properties:
                      lastTransitionTime:
                        description: Last time the condition transitioned from one status to another.
                        format: date-time
                        type: string
                      lastUpdateTime:
                        description: The last time this condition was updated.
                        format: date-time
                        type: string
                      message:
                        description: A human readable message indicating details about the transition.
                        type: string
                      reason:
                        description: The reason for the condition's last transition.
                        type: string
                      status:
                        description: 'Status of the condition for a operator user. Valid values for "Synced": "True", "False", or "Unknown".'
                        type: string
                      type:
                        description: 'Type of condition for a operator user. Valid value: "Configured"'
                        type: string
                    required:
                      - status
                      - type
                    type: object
                  type: array
                observedGeneration:
                  description: ObservedGeneration reflects the generation most recently observed by the htpasswd-operator.
                  format: int64
                  type: integer
              type: object