---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: htpasswd-operator-ro
rules:
  - apiGroups: ["flanga.io"]
    resources: ["htpasswd-users"]
    verbs: ["watch", "list", "get"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: htpasswd-operator-ro
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: htpasswd-operator-ro
subjects:
  - kind: ServiceAccount
    name: htpasswd-controller-sa
