---
kind: HtpasswdUser
apiVersion: flanga.io/v1
metadata:
  name: htpasswd-admin
spec:
  username:
    value: admin
  password:
    value: adminPassword
---
kind: HtpasswdUser
apiVersion: flanga.io/v1
metadata:
  name: htpasswd-hotel
spec:
  username:
    value: hotel
  password:
    value: trivago
---
kind: HtpasswdUser
apiVersion: flanga.io/v1
metadata:
  name: htpasswd-hotel2
spec:
  username:
    value: hotel2
  password:
    value: trivago2
---
kind: HtpasswdUser
apiVersion: flanga.io/v1
metadata:
  name: htpasswd-testuser1
spec:
  username:
    secretKeyRef:
      name: htpasswd-users
      key: test1-username
  password:
    secretKeyRef:
      name: htpasswd-users
      key: test1-password
---
kind: HtpasswdUser
apiVersion: flanga.io/v1
metadata:
  name: htpasswd-configuser
spec:
  username:
    configMapKeyRef:
      name: htpasswd-configusers
      key: test-username
  password:
    configMapKeyRef:
      name: htpasswd-configusers
      key: test-password