apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: htpasswd-users.flanga.io
spec:
  group: flanga.io
  names:
    kind: HtpasswdUser
    singular: htpasswd-user
    plural: htpasswd-users
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: HtpasswdUser reflects reflect an user/password in a htpasswd file
          type: object
          required:
            - spec
            - apiVersion
            - kind
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              anyOf:
                - required:
                    - username
                    - password
              properties:
                username:
                  type: object
                  oneOf:
                    - required: [ configMapKeyRef ]
                    - required: [ secretKeyRef ]
                    - required: [ value ]
                  properties:
                    configMapKeyRef:
                      type: object
                      required:
                        - name
                        - key
                      properties:
                        name:
                          type: string
                        key:
                          type: string
                        optional:
                          type: boolean
                    secretKeyRef:
                      type: object
                      required:
                        - name
                        - key
                      properties:
                        name:
                          type: string
                        key:
                          type: string
                        optional:
                          type: boolean
                    value:
                      type: string
                password:
                  type: object
                  oneOf:
                    - required: [ configMapKeyRef ]
                    - required: [ secretKeyRef ]
                    - required: [ value ]
                  properties:
                    configMapKeyRef:
                      type: object
                      required:
                        - name
                        - key
                      properties:
                        name:
                          type: string
                        key:
                          type: string
                        optional:
                          type: boolean
                    secretKeyRef:
                      type: object
                      required:
                        - name
                        - key
                      properties:
                        name:
                          type: string
                        key:
                          type: string
                        optional:
                          type: boolean
                    value:
                      type: string
