name: Deploy Htpasswd Operator to Docker
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
jobs:
  test:
    name: "Test Htpasswd Operator"
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.x
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run Linter
        run: make lint
      - name: Build
        run: make build
  dist:
    name: Deploy to Container Registry
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/v1'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: mowirth/htpasswd-operator:latest